import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@utils/auth-context";
import Navbar from "@components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Tournaments by Sunsab",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<AuthContextProvider>
			<html lang="en">
			
				<body className={inter.className}>
					<Navbar />
					{children}
					</body>
			</html>
		</AuthContextProvider>
	);
}
